feat: 레거시 전환 및 class 이름 변경 (미디어위키 1.36 대응)
dodawiki/mediawiki-namumark pull request #5
Opened 2021-03-11 16:38 UTC by ddarkr

일단은 문제 없어 보이는 것 같긴 함. 다만 소스를 너무 확 엎어버린 감이 있음...

2021-03-11 16:56 UTC, ddarkr commented
<table>
<tr>
	<td colspan=2> 테스트 정보
<tr>
	<td> 미디어위키
	<td> 1.36.0-alpha (1bdf3ec)
<tr>
	<td> PHP
	<td> 8.0.2
</table>

[나무위키의 `코로나바이러스감염증-19/경과/2020년 10월`](https://namu.wiki/w/%EC%BD%94%EB%A1%9C%EB%82%98%EB%B0%94%EC%9D%B4%EB%9F%AC%EC%8A%A4%EA%B0%90%EC%97%BC%EC%A6%9D-19/%EA%B2%BD%EA%B3%BC/2020%EB%85%84%2010%EC%9B%94) 문서를 기준으로 테스트했을 때, 일부 미지원되는 문법으로 깨지는 부분을 제외한다면 전반적으로 정상 동작하는 것으로 판단.

2021-03-12 14:44 UTC, PlavorSeol requested changes

2021-03-12 14:44 UTC, PlavorSeol commented on extension.json
> +		"InternalParseBeforeLinks": "NamuMarkExtension::markParse"
서로 다른 hook이 동일한 함수를 사용하는 이유가 뭐죠?

2021-03-12 15:09 UTC, ddarkr commented on extension.json
> +		"InternalParseBeforeLinks": "NamuMarkExtension::markParse"
`InternalParseBeforeLinks` 훅 사용시 틀에는 나무마크가 적용되지 않는 문제가 있어 적용한 결과입니다. markParse가 두 번 실행되어 파싱이 지연되는 문제가 생길 수 있어 추후 문법 분리도 계획하고 있습니다.

2021-03-18 22:45 UTC, merged